<a href="https://colab.research.google.com/github/mohaseen1/FSDSRegression/blob/main/keras_tuner_hyperparameter_tuning_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd


In [7]:
df=pd.read_csv('/content/archive (1) (1) (1).zip')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [8]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [9]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
x.shape

(768, 8)

In [11]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [12]:
y.shape

(768,)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()


In [14]:
x=scaler.fit_transform(x)

In [15]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
import tensorflow as tf

In [19]:
LAYERS=[
    tf.keras.layers.Dense(32,activation='relu',input_dim=8),
    tf.keras.layers.Dense(1,activation='sigmoid')
]

model=tf.keras.models.Sequential(LAYERS)




In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [21]:
LOSS_FUNCTION='binary_crossentropy'
OPTIMIZER='Adam'
METRICS=['accuracy']

model.compile(loss=LOSS_FUNCTION,
              optimizer=OPTIMIZER,
              metrics=METRICS)

In [22]:
model.fit(x_train,y_train,batch_size=32,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10
20/20 [==============================] - 6s 14ms/step - loss: 0.7123 - accuracy: 0.6107 - val_loss: 0.6893 - val_accuracy: 0.5974
Epoch 2/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6522 - accuracy: 0.6678 - val_loss: 0.6367 - val_accuracy: 0.6429
Epoch 3/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6090 - accuracy: 0.6759 - val_loss: 0.6044 - val_accuracy: 0.6688
Epoch 4/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5770 - accuracy: 0.6906 - val_loss: 0.5777 - val_accuracy: 0.6948
Epoch 5/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5512 - accuracy: 0.7020 - val_loss: 0.5594 - val_accuracy: 0.6883
Epoch 6/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5317 - accuracy: 0.7248 - val_loss: 0.5449 - val_accuracy: 0.7143
Epoch 7/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5146 - accuracy: 0.7329 - val_loss: 0.5330 - val_accuracy: 0.7403
Epoch 8/10
20/20 [=

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [24]:
# how to select best optimizer
#how select no of nodes/neurons in a layers
#how to select no. of layers
#all in one model

In [25]:
!pip install -U keras-tuner

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 4.0 MB/s eta 0:00:00


In [26]:
import keras_tuner as kt

In [27]:
def build_model(hp):

  LAYERS=[
    tf.keras.layers.Dense(32,activation='relu',input_dim=8),
    tf.keras.layers.Dense(1,activation='sigmoid')
]

  model=tf.keras.models.Sequential(LAYERS)


  LOSS_FUNCTION='binary_crossentropy'
  OPTIMIZER=hp.Choice('optimizer',values=['adam','sgd','rmsprop','addadelta'])
  METRICS=['accuracy']

  model.compile(loss=LOSS_FUNCTION,
              optimizer=OPTIMIZER,
              metrics=METRICS)

  return model


In [28]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5)

In [29]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7207792401313782

Best val_accuracy So Far: 0.7467532753944397
Total elapsed time: 00h 00m 07s


In [30]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [31]:
model=tuner.get_best_models(num_models=1)[0]

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10
20/20 [==============================] - 2s 13ms/step - loss: 0.5201 - accuracy: 0.7362 - val_loss: 0.5363 - val_accuracy: 0.7662
Epoch 2/10
20/20 [==============================] - 0s 5ms/step - loss: 0.5075 - accuracy: 0.7541 - val_loss: 0.5281 - val_accuracy: 0.7662
Epoch 3/10
20/20 [==============================] - 0s 5ms/step - loss: 0.4966 - accuracy: 0.7590 - val_loss: 0.5217 - val_accuracy: 0.7597
Epoch 4/10
20/20 [==============================] - 0s 4ms/step - loss: 0.4881 - accuracy: 0.7606 - val_loss: 0.5170 - val_accuracy: 0.7792
Epoch 5/10
20/20 [==============================] - 0s 5ms/step - loss: 0.4812 - accuracy: 0.7704 - val_loss: 0.5119 - val_accuracy: 0.7662
Epoch 6/10
20/20 [==============================] - 0s 5ms/step - loss: 0.4747 - accuracy: 0.7720 - val_loss: 0.5103 - val_accuracy: 0.7662
Epoch 7/10
20/20 [==============================] - 0s 5ms/step - loss: 0.4701 - accuracy: 0.7752 - val_loss: 0.5093 - val_accuracy: 0.7662
Epoch 8/10
20/20 [=

How to select no. of nodels/neurons in a layers

In [34]:
def build_model(hp):

  units=hp.int('units',min_value=8,max_value=128, step=8)

  LAYERS=[
    tf.keras.layers.Dense(units=units,activation='relu',input_dim=8),
    tf.keras.layers.Dense(1,activation='sigmoid')
]

  model=tf.keras.models.Sequential(LAYERS)


  LOSS_FUNCTION='binary_crossentropy'
  OPTIMIZER='rmsprop'
  METRICS=['accuracy']

  model.compile(loss=LOSS_FUNCTION,
              optimizer=OPTIMIZER,
              metrics=METRICS)

  return model

In [36]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5,
                      directory='mydir')

AttributeError: ignored

In [38]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

How to select no. layers

In [39]:
import tensorflow as tf
import keras
from keras.layers import Dense
from keras.models import Sequential

In [43]:
def build_model(hp):
  model=Sequential()
  model.add(Dense(88,activation='relu',input_dim=8))

  for i in range(hp.int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(88,activation='relu'))

    model.add(Dense(1,activation='sigmoid'))

  LOSS_FUNCTION='binary_crossentropy'
  OPTIMIZER='rmsprop'
  METRICS=['accuracy']

  model.compile(loss=LOSS_FUNCTION,
              optimizer=OPTIMIZER,
              metrics=METRICS)

  return model


In [44]:
tuner=kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5,
                      directory='mydir1')

AttributeError: ignored

In [45]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [46]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [47]:
model=tuner.get_best_models(num_models=1)[0]

In [48]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________
